### ISSUE TITLE
Add custom integration to Wombat (4 hours)

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/konnektive_integration#1]
This guide look useful: https://support.wombat.co/hc/en-us/articles/204097155-How-to-Write-and-Register-a-Custom-Integration

**Comment by apeacox** [comment]
added integration to staging environment

**Comment by apeacox** [comment]
I've created an heroku app for this:  nb-wombat-konnektive waiting to give you owner privileges, I'll keep developer privileges for me :-) the app can work with staging and production, because it's just a proxy

**Comment by onedanshow** [comment]
I'd like to get the polling down to 10 minutes and let Wombat resolve the duplicates. We'll have overnight orders that we want to get through quickly

**Comment by apeacox** [comment]
ok, changed the integration. the integration now polls for the current day. I've also changed wombat settings to poll every 10 minutes.

moving the task to preview

**Comment by onedanshow** [comment]
What is the error that is in staging of Wombat?  https://my.wombat.co/accounts/53b30e11736d6155b1020000/notifications/?utf8=%E2%9C%93&object_ref=&subject=&flow_id=&object_type=&status=Unresolved&search=1

Have the test orders that are in Konnektive successfully imported into Wombat?

Thanks!

**Comment by onedanshow** [comment]
@apeacox  What’s the current status here? Thanks!

**Comment by apeacox** [comment]
it happens when it doesn't find any data from the konnektive API. eg: when there weren't any orders for a given day. you can ignore that specific error

**Comment by apeacox** [comment]
btw, the integration should now work correctly

**Comment by onedanshow** [comment]
Can you make the error not happen if there are not any orders?  No need to clear those out regularly.
