### ISSUE TITLE
Setup this integration

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/konnektive_integration#4]
You might pick one here to mimic: https://github.com/wombat

Or use this guide: 
https://support.wombat.co/hc/en-us/articles/202315564-Custom-Integration-Tutorial
https://support.wombat.co/hc/en-us/articles/202557620-Build-your-own-Integrations

**Comment by apeacox** [comment]
is there any doc for konnektive APIs? perhaps building a simple ruby script and a cron job should be enough for the task. however, I can't find a place for APIs :-(

**Comment by onedanshow** [comment]
The docs are here: https://api.konnektive.com/docs/order_query/
